# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:  datasource:    url: jdbc:mysql://localhost:3306/bus1
    username: root
    password: admin
  application:    name: TuyenService

server:  port: 8088
# Hibernate

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
    show-sql: true

eureka:  client:    service-url:      defaultZone: http://localhost:7777/eureka
